# We can't remove volumes in a compose override, for the test configuration using the final containers
# we don't want the volumes so this is the default override file to add the volumes in the dev case
# any override will need to include these volumes to use them.
# see:  https://github.com/docker/compose/issues/3729
---
services:
  nautobot:
    command: "nautobot-server runserver 0.0.0.0:8080"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../:/source"
    healthcheck:
      disable: true
  docs:
    entrypoint: "mkdocs serve -v -a 0.0.0.0:8080 --no-directory-urls"
    ports:
      - "127.0.0.1:8001:8080"
    volumes:
      - "../docs:/source/docs:ro"
      - "../mkdocs.yml:/source/mkdocs.yml:ro"
    image: "nautobot-fsus/nautobot:${NAUTOBOT_VER}-py${PYTHON_VER}"
    healthcheck:
      disable: true
    tty: true
  worker:
    volumes:
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../:/source"
# To expose postgres or redis to the host uncomment the following
#  postgres:
#    ports:
#      - "127.0.0.1:5432:5432"
#  redis:
#    ports:
#      - "127.0.0.1:6379:6379"
