---
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/main/nautobot-app-fsus/docs"
site_dir: "nautobot_fsus/static/nautobot_fsus/docs"
site_name: "Nautobot Field Serviceable Units"
site_url: "https://github.com/NVIDIA/nautobot-app-fsus"
repo_url: "https://github.com/NVIDIA/nautobot-app-fsus"
theme:
  name: "material"
  navigation_depth: 4
  hljs_languages:
    - "django"
    - "yaml"
  features:
    - "content.code.copy"
    - "navigation.tabs"
    - "navigation.tabs.sticky"
    - "navigation.tracking"
    - "search.highlight"
    - "search.share"
    - "search.suggest"
  favicon: "assets/favicon.ico"
  logo: "assets/nvidia-logo-vert-rgb-wht-for-screen.png"
  icon:
    repo: "fontawesome/brands/gitlab"
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to system preference
extra_css:
  - "extra.css"

markdown_extensions:
  - "admonition"
  - "attr_list"
  - "def_list"
  - toc:
      permalink: true
  - "footnotes"
  - "md_in_html"
  - "pymdownx.details"
  - "pymdownx.highlight":
      anchor_linenums: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
  - "sane_lists"

plugins:
  - "search"
  - "include-markdown"
  - "mkdocs-version-annotations"
  - "mkdocstrings":
      default_handler: "python"
      handlers:
        python:
          paths: ["."]
          options:
            show_root_heading: true

watch:
  - "README.md"

nav:
  - Introduction: "index.md"
  - User Guide:
      - Overview: "user/index.md"
      - Field Serviceable Units: "user/fsus.md"
      - Model Details:
          - CPU Type: "models/cputype.md"
          - CPU Template: "models/cputemplate.md"
          - CPU: "models/cpu.md"
          - Disk Type: "models/disktype.md"
          - Disk Template: "models/disktemplate.md"
          - Disk: "models/disk.md"
          - Fan Type: "models/fantype.md"
          - Fan Template: "models/fantemplate.md"
          - Fan: "models/fan.md"
          - GPU Type: "models/gputype.md"
          - GPU Template: "models/gputemplate.md"
          - GPU: "models/gpu.md"
          - GPU Baseboard Type: "models/gpubaseboardtype.md"
          - GPU Baseboard Template: "models/gpubaseboardtemplate.md"
          - GPU Baseboard: "models/gpubaseboard.md"
          - HBA Type: "models/hbatype.md"
          - HBA Template: "models/hbatemplate.md"
          - HBA: "models/hba.md"
          - Mainboard Type: "models/mainboardtype.md"
          - Mainboard Template: "models/mainboardtemplate.md"
          - Mainboard: "models/mainboard.md"
          - NIC Type: "models/nictype.md"
          - NIC Template: "models/nictemplate.md"
          - NIC: "models/nic.md"
          - Other FSU Type: "models/otherfsutype.md"
          - Other FSU Template: "models/otherfsutemplate.md"
          - Other FSU: "models/otherfsu.md"
          - PSU Type: "models/psutype.md"
          - PSU Template: "models/psutemplate.md"
          - PSU: "models/psu.md"
          - RAM Module Type: "models/rammoduletype.md"
          - RAM Module Template: "models/rammoduletemplate.md"
          - RAM Module: "models/rammodule.md"
  - Administrator Guide:
      - Install: "admin/install.md"
      - Upgrade: "admin/upgrade.md"
      - Uninstall: "admin/uninstall.md"
      - Release Notes:
          - "admin/release_notes/index.md"
          - v1.0: "admin/release_notes/version_1.0.md"
  - Developer Guide:
      - Contributing to the App: "dev/contributing.md"
      - Development Environment: "dev/dev_env.md"
      - Code Reference:
          - "dev/code_reference/index.md"
          - Package: "dev/code_reference/package.md"
          - API: "dev/code_reference/api.md"
          - Models: "dev/code_reference/models.md"
