# Generated by Django 3.2.25 on 2024-08-16 21:07

from django.db import migrations, models
from django.db.models import deletion
from nautobot.core.models.fields import TagsField
from nautobot.extras.models.statuses import StatusField


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_fsus", "0002_null_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpu",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="cpu",
            name="status",
            field=StatusField(
                on_delete=deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="cpu",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="cputemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="cputype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="cputype",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="disk",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="disk",
            name="status",
            field=StatusField(
                on_delete=deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="disk",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="disktemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="disktype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="disktype",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="fan",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="fan",
            name="status",
            field=StatusField(
                on_delete=deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="fan",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="fantemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="fantype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="fantype",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="status",
            field=StatusField(
                on_delete=deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="gpubaseboard",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpubaseboard",
            name="status",
            field=StatusField(
                on_delete=deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="gpubaseboard",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="gpubaseboardtemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpubaseboardtype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpubaseboardtype",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="gputemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="gputype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="gputype",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="hba",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="hba",
            name="status",
            field=StatusField(
                on_delete=deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="hba",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="hbatemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="hbatype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="hbatype",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="mainboard",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="mainboard",
            name="status",
            field=StatusField(
                on_delete=deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="mainboard",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="mainboardtemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="mainboardtype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="mainboardtype",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="nic",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="nic",
            name="status",
            field=StatusField(
                on_delete=deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="nic",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="nictemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="nictype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="otherfsu",
            name="status",
            field=StatusField(
                on_delete=deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="nictype",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="otherfsu",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="otherfsu",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="otherfsutemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="otherfsutype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="otherfsutype",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="psu",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="psu",
            name="status",
            field=StatusField(
                on_delete=deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="psu",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="psutemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="psutype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="psutype",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="rammodule",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="rammodule",
            name="status",
            field=StatusField(
                on_delete=deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_related",
                to="extras.status",
            ),
        ),
        migrations.AlterField(
            model_name="rammodule",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="rammoduletemplate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="rammoduletype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="rammoduletype",
            name="tags",
            field=TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterUniqueTogether(
            name="cpu",
            unique_together={("name", "device"), ("name", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="disk",
            unique_together={("name", "device"), ("name", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="fan",
            unique_together={("name", "device"), ("name", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="gpu",
            unique_together={("name", "device"), ("name", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="gpubaseboard",
            unique_together={("name", "device"), ("name", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="hba",
            unique_together={("name", "device"), ("name", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="mainboard",
            unique_together={("name", "device"), ("name", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="nic",
            unique_together={("name", "device"), ("name", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="otherfsu",
            unique_together={("name", "device"), ("name", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="psu",
            unique_together={("name", "device"), ("name", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="rammodule",
            unique_together={("name", "device"), ("name", "location")},
        ),
    ]
