---
name: "CICD Nautobot FSUs"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
      - "dev"
      - "ltm-*"
    tags:
      - "v*"
  pull_request: ~

jobs:
  bandit:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Linting: bandit"
        run: poetry run bandit --recursive nautobot_fsus --configfile .bandit.yml

  pydocstyle:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Linting: pydocstyle"
        run: poetry run pydocstyle nautobot_fsus

  flake8:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Linting: flake8"
        run: poetry run flake8 nautobot_fsus

  pylint:
    needs:
      - "bandit"
      - "pydocstyle"
      - "flake8"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: true
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Linting: pylint"
        run: poetry run pylint --init-hook "import nautobot; nautobot.setup()" --rcfile pyproject.toml nautobot_fsus

  mypy:
    needs:
      - "pylint"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Linting: mypy"
        run: poetry run mypy nautobot_fsus

  unittests:
    needs:
      - "mypy"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: true
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Run tests"
        run: poetry run coverage xml --include=nautobot_fsus/* --omit *migrations*
